server:
  port: 8082
spring:
  application:
    name: user-consume # 应用名称
  cloud:
    loadbalancer:
      retry:
        enabled: true # 开启Spring Cloud的重试功能
eureka:
  client:
    register-with-erueka: true
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找

#user-service:
#  ribbon:
#    ConnectTimeout: 250 # 连接超时时间(ms)
#    ReadTimeout: 1000 # 通信超时时间(ms)
#    OkToRetryOnAllOperations: true # 是否对所有操作重试
#    MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
#    MaxAutoRetries: 1 # 同一实例的重试次数

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 6000 # 设置hystrix的超时时间为6000ms,Hystrix的超时时间一定要大于Robbin的重试时间。

feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能,配合 hystrix 一起使用
  compression:
    request:
      enabled: true # 开启请求压缩
      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
      min-request-size: 2048 # 设置触发压缩的大小下限
    response:
      enabled: true # 开启响应压缩